### ISSUE TITLE
Deno.HttpClient

### ISSUE THREAD

**Issue by webdev3301** [cmd-johnson/deno-oauth2-client#14]
Hello. I just wanted to post an update regarding the [Deno.HttpClient](https://doc.deno.land/https/raw.githubusercontent.com/denoland/deno/main/cli/dts/lib.deno.unstable.d.ts#Deno.HttpClient). Is it possible you can use this instead of OAK?

It would be nice to have a 100% deno solution.

**Comment by cmd-johnson** [comment]
Hi there!
Apart from the `*_test.ts` files, this module does not directly depend any other modules, not even ones from the `std` library. I'm using `fetch` for all outgoing HTTP requests.

This module leaves handling requests originating from the user up to the developer, and while the example in the README shows how this can be done using oak, the same thing can easily be achieved with [Deno's std HTTP Server](https://deno.land/std/http/server.ts). I've got an example for that [here](https://github.com/cmd-johnson/deno-oauth2-client/blob/master/examples/http.ts).

Also `Deno.HttpClient` appears to work in conjunction with `fetch`, i.e. is intended for outgoing requests. If customizing the `fetch` behavior is what you want, I might consider adding an option to override the usage of the inbuild `fetch` function with a custom implementation.

**Comment by thgh** [comment]
@webdev3301 you may be looking for this [http example](https://github.com/cmd-johnson/deno-oauth2-client/blob/master/examples/http.ts)
