### ISSUE TITLE
Examples broken - the JSON entry 'name' changed to 'login'

### ISSUE THREAD

**Issue by psytrap** [cmd-johnson/deno-oauth2-client#18]
The JSON entry 'name' has changed to 'login'. This breaks the examples and nothing is shown in the login page. After changing it to 'login' the GitHub user name is shown.

https://github.com/cmd-johnson/deno-oauth2-client/blame/master/README.md#L54

https://github.com/cmd-johnson/deno-oauth2-client/blame/master/examples/oak.ts#L31

https://github.com/cmd-johnson/deno-oauth2-client/blob/master/examples/http.ts#L49

Here a working example for deno.dev hosting: https://dash.deno.com/projects/dry-pigeon-88

**Comment by cmd-johnson** [comment]
Thanks for filing this issue!

I wasn't able to reproduce this on my end, however. After setting my own client ID and secret, the example works just fine for me. The [documentation of the https://api.github.com/user endpoint](https://docs.github.com/en/rest/users/users#get-the-authenticated-user) includes both the `login` and `name` fields, so I don't see a reason there, why it wouldn't work.

Can you show me the exact code that didn't work for you?

**Comment by psytrap** [comment]
I think I found the root cause. My name is not set on my "Public Profile" settings for github. To be correct the result for name is then "null" on my profile. In your GitHub profile I see "Jonas Auer" as name and I guess "cmd-johnson" is your login id.

**Comment by cmd-johnson** [comment]
Huh, you're right, the `name` field in GitHub's response is nullable:
```json
"name": {
  "type": [
    "string",
    "null"
  ],
  "examples": [
    "monalisa octocat"
  ]
},
```

To keep the examples simple, I'll update them to use the `title` as you suggested! :+1:
