### ISSUE TITLE
suggestion: publish to JSR

### ISSUE THREAD

**Issue by iuioiua** [cmd-johnson/deno-oauth2-client#52]
[JSR](https://jsr.io/) is Deno's new JavaScript registry. Publishing here will allow dependent modules to publish to JSR, too. Some work would be required, but it wouldn't be hard. I'd be happy to lend a hand.

References:
1. [JSR's docs on publishing packages](https://jsr.io/docs/publishing-packages)
2. [Deno's tool for converting deno.land/x modules to JSR packages](https://jsr.io/@deno/x-to-jsr)

**Comment by cmd-johnson** [comment]
Thank you for your PR! (#55)

My current understanding for the road to JSR for this module is this:

- [x] PR for making the library JSR-compatible (#55)
    - [x] Update types to not include [slow types](https://jsr.io/docs/about-slow-types) in exports
    - [x] Update imports to use import maps
    - [x] Update dependencies to use `jsr:` instead of importing from `https://deno.land/x/`
    - [x] Bump the version to `2.0.0` because these changes aren't compatible with `https://` imports and now require importing from JSR
- [x] PR for adding a deprecation notice for people still using the version hosted on deno.land/x
    - [x] Minor version bump
    - [x] Updated `README.md` with deprecation notice and migration instructions

After these are ready we can
1. Merge the deprecation PR and tag it, triggering a final release on deno.land/x
2. Remove the webhook that triggers new releases on deno.land/x
3. Merge #55, which should already take care of releasing 2.0.0 on JSR

Does this sound about right?

**Comment by cmd-johnson** [comment]
Resolved in #55 and released in [version 2.0.0](https://github.com/cmd-johnson/deno-oauth2-client/tree/2.0.0) as [`@cmd-johnson/oauth2-client`](https://jsr.io/@cmd-johnson/oauth2-client)
