### ISSUE TITLE
Request: Ability to set `prompt` or `access_type`

### ISSUE THREAD

**Issue by RaresGeo** [cmd-johnson/deno-oauth2-client#58]
Hi, to avoid the XY problem I will just state from the start that my issue is not receiving a refresh token from Google.

After looking online a bunch, the three things people mention are:
1. Setting `access_type` to offline
2. Setting the `'offline_access'` scope (this does not appear to exist)
3. Setting `prompt` to `'consent'` to force the consent screen (which is not appearing at all for me, even after revoking access to the app)

I am unable to find any way to do this and I am unsure if I am doing something wrong, but I can't seem to be able to figure out how to get Google to issue the refresh token, and all documentation just says "if the provider issues a refresh token," but not how to get it to issue one.

**Comment by cmd-johnson** [comment]
I got this to work using a few small changes to the [http example](https://github.com/cmd-johnson/deno-oauth2-client/blob/main/examples/http.ts): https://gist.github.com/cmd-johnson/4e72ddacde79fb314632a61df854634d

The only real changes were:
- [I updated the client configuration to point to the google endpoints](https://gist.github.com/cmd-johnson/4e72ddacde79fb314632a61df854634d#file-oauth2-client-google-ts-L9-L18)
    - I also added the openid, email and profile scopes so I can use the userinfo endpoint later on. They shouldn't all be required, but you have to request at least one scope or Google will throw an error at you after the redirect.
- [I'm setting the `access_type` url parameter to `offline` before redirecting the user](https://gist.github.com/cmd-johnson/4e72ddacde79fb314632a61df854634d#file-oauth2-client-google-ts-L47)
- [By setting the `prompt` url parameter to `consent`, I was able to always get a refresh token from Google](https://gist.github.com/cmd-johnson/4e72ddacde79fb314632a61df854634d#file-oauth2-client-google-ts-L48)
- [If a refresh token was returned, I'm using it immediately to get new tokens](https://gist.github.com/cmd-johnson/4e72ddacde79fb314632a61df854634d#file-oauth2-client-google-ts-L78-L80)
- [I'm then using the access token to query the userinfo endpoint](https://gist.github.com/cmd-johnson/4e72ddacde79fb314632a61df854634d#file-oauth2-client-google-ts-L82-L90)

That works consistently for me.

(Note to self: [this](https://myaccount.google.com/connections) is the page for managing all Apps connected to a Google account)

**Comment by RaresGeo** [comment]
Thank you for the very quick reply! My problem was that I had expected to find a way to do it directly through the interfaces provided by the client object, but instead I should have simply modified the uri.

This solves my problem :)
